Algoritmo "par_impar"

Var
//Faça um programa que leia um número e diga se ele é
// par ou ímpar

//variaveis
numero_um: inteiro

Inicio
//Pedir numero ao usuário
        escreval("Digite um número: ")
        leia(numero_um)
//Fazer o cálculo
        se numero_um % 2=0 entao
           escreval("O número é par!")
        senao
             escreval("O número é ímpar")
        fimse

Fimalgoritmo