Algoritmo "ValidarSenha_enquanto"

Var
 senha: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         escreval("Digite a senha: ")
         leia(senha)
         
         enquanto senha <> 1234 faca
                  escreval("Senha incorreta. Digite novamente:")
                  leia(senha)
         fimenquanto
         escreval("Senha correta! Acesso liberado.")

Fimalgoritmo